import React, { useEffect } from "react";
import { useRouter } from "next/router"; // Import useRouter

import Head from "next/head";

import { useSession } from "next-auth/react";
import Footer from "@/components/footer/Footer";
import AthleteList from "@/components/bedrock_chat/AthleteList";
import ChatingArea from "@/components/bedrock_chat/ChatingArea";
import AthleteChatSidebar from "@/components/bedrock_chat/AthleteChatSidebar";

const ChatMainContent = () => {
  const { data: session, status } = useSession(); // Get session and status
  const router = useRouter(); // Initialize useRouter

  useEffect(() => {
    if (status === "loading") return; // Do nothing while loading
    if (!session) {
      // Redirect to login if not authenticated
      router.push("/openai/openAILogin"); // Use router.push for redirection
    }
  }, [session, status, router]); // Add router to dependencies

  if (status === "loading") {
    return <div>Loading...</div>; // Show loading state
  }

  return (
    <>
      <Head>
        <title>OpenAI - Athlete Chatbot</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/favicon.png" />
      </Head>
      <div className="main-content">
        <div className="chatting-panel">
          <div className="d-flex">
            <div className="">
              <div className="panel-body border-bottom panelbody-openai"></div>
            </div>

            <div className="panel position-relative bedrock-custom-panel">
              <ChatingArea />
            </div>
            <AthleteChatSidebar />
          </div>
        </div>

        <Footer />
      </div>
    </>
  );
};

export default ChatMainContent;
