import React from "react";
import Head from "next/head";
import Footer from "@/components/footer/Footer";
import BirthFIleInputSection from "@/components/forms/openai/BirthFIleInputSection";
import CategorySection from "@/components/add-new-product/CategorySection";

const PdfBookSummariserMainContent = () => {
  return (
    <>
      <Head>
        <title>Projects - Pdf Summariser</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/favicon.png" />
      </Head>
      <div className="main-content">
        <BirthFIleInputSection />

        <Footer />
      </div>
    </>
  );
};

export default PdfBookSummariserMainContent;
