import React from "react";
import Footer from "@/components/footer/Footer";
import Head from "next/head";
import DashboardBreadcrumb2 from "@/components/breadcrumb/DashboardBreadcrumb2";
import AddNewImage from "@/components/nid/AddNewImage";
import Preview from "@/components/nid/Preview";

const NIDBackMainContent = () => {
  return (
    <>
      <Head>
        <title>Digiboard - Category</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="assets/favicon.png" />
      </Head>
      <div className="main-content">
        <DashboardBreadcrumb2 title={"Vehicle Number Plate"} />
        <div className="row g-4">
          <AddNewImage />
          <Preview />
        </div>

        <Footer />
      </div>
    </>
  );
};

export default NIDBackMainContent;
