import React from "react";
import Footer from "@/components/footer/Footer";
import Head from "next/head";
import DashboardBreadcrumb2 from "@/components/breadcrumb/DashboardBreadcrumb2";
import AddNewImage from "@/components/trade-verify/AddNidImage";
import Preview from "@/components/trade-verify/Preview";
import AddNidImage from "@/components/trade-verify/AddNidImage";
import CompareAndVerify from "@/components/trade-verify/CompareAndVerify";
import AddTradeLicenseImage from "@/components/trade-verify/AddTradeLisenseImage";

const TradeCertificateMainContent = () => {
  return (
    <>
      <Head>
        <title>Digiboard - Category</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="assets/favicon.png" />
      </Head>
      <div className="main-content">
        <DashboardBreadcrumb2 title={"Trade license"} />
        <div className="row g-4">
          <AddNidImage />
          <AddTradeLicenseImage />
          <CompareAndVerify />
          {/* <AddNewImage />
          <AddNewImage />
          <Preview /> */}
        </div>

        <Footer />
      </div>
    </>
  );
};

export default TradeCertificateMainContent;
